### ISSUE TITLE
Consider Webpack instead of Browserify

### ISSUE THREAD

**Issue by omeid** [mserajnik/rtsn#1]
Hi Michael,

Very interesting work, but I was wondering if there was a chance you could consider webpack instead of browserify?

Why? Because webpack has won over and there is many plugins and loaders than browserify.

**Comment by mserajnik** [comment]
Hi Omeid,

thank you for your feedback.

I've actually started working on a package that uses Webpack instead of gulp. However, I've run into some issues though where gulp clearly wins over Webpack (mainly when using multiple HTML/Pug templates without the need to manually include them each time – I'd like to keep it easy for the end user).

But your suggestion is keeping the gulp tasks and just replacing Browserify with Webpack, right? Should Webpack only be used for the JS then or should I also look into bundling CSS with it?

**Comment by omeid** [comment]
Yeah, I was thinking of keeping gulp and leveraging webpack for bundling, but then things like _critical_ begs the question of where should it go, gulp or as a webpack plugin? I think there is arguments to be made for both way, so I am not exactly sure.

**Comment by mserajnik** [comment]
I will look into it when i find the time. I'll probably make it a choice for the user if he wants to use Webpack or the current version. Might take a few weeks though since I'm currently a little bit short on spare time.

**Comment by mserajnik** [comment]
After more consideration and some testing, I've decided not to implement webpack into rtsn.

From my experience with it, webpack works best when it's used the way it's intended. That is, to bundle everything up into a module, including the markup, images and so on. This means it works really well when you have a specific configuration for a project and know how to work with it. But it also makes it hard to include in a package that should allow for a broad range of use cases.

To be more specific, rtsn is designed with two main principles in mind:

- It should be easy to use and require no additional configuration once it's set up (the user shouldn't need to know how exactly it works)
- The output should be in a way that allows it to be used for integration in content management system themes etc. by just taking everything form the build directory and starting to modify it as needed

Both principles are really hard to keep if I were to include webpack:

The way webpack is designed (even if the markup gets not bundled up in the module itself and is instead used with something like [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin)) makes it practically impossible to set it up in a way that the user doesn't need to add additional configuration each time he wants another "page". That goes against the first principle.

To counter that, I've tried setting it up in a way that it reads all top-level `.html`/`.pug` files in a directory and create one output `.html` for each, but that doesn't work once the user decides to add a new top-level input while [webpack-dev-server](https://github.com/webpack/webpack-dev-server) is running. And automatically restarting the server when a new file is added (or an old one removed) doesn't feel very right to me either.

Aside from that, having the output in dedicated `.html` files instead of it being bundled up in the module just straight up breaks hot module replacement (which would be another step down from the current setup which allows for JavaScript and CSS to be injected without the need to refresh the browser tab). But not doing so makes it basically impossible the take the output and build, e.g., a WordPress theme out of it, which goes against rtsn's second principle.

I would much rather start a new project entirely based on webpack that is designed specifically for creating static sites (where you don't care about not being able to take the output and build something additional from it) or projects running Angular/React/Vue/etc. In fact, that's something I could use myself (instead of copy/pasting my existing webpack configuration and making adjustments for an hour every time).

Due to time constraints, I won't be able to start that project until the end of the year (or even later), so I won't make any promises as to when that'll be available. Considering how fast time flows in the JS world, we might already be using something else than webpack by then. :D

In the meantime, I'll close this issue, but if anyone feels up to the task of adding webpack to rtsn without making it more complicated for the end user and without downgrading/removing any of the available features, I'm happy to accept pull requests. :)
